### PR TITLE
attempt to fix memory leak and clear resources on connection end

### PR DESCRIPTION
**Pull request by jaylu**
this is what the leaking found so far.

### CODE REVIEW

**Comment by jaylu** [comment]
The build failed because of test EventsTest failed. 

The reason is because when the ResponseCompleteListener callback is invoked, it pass ResponseInfo (which is the HttpExchange) as parameter, by then, the  HttpExchange.completedSuccessfully() is returning false. 

But later, inside the muServer, the corresponding HttpExchange will be updated and the result will returning true finally. 

Ideally, the ResponseCompleteListener should executed when the Http2 stream finished, but now it's not. I might because of the Http2ConnectionFlowControl delay the execution, and the runnable put into the ctx.eventLoop later. Hope this info helps.

**Comment by jaylu** [comment]
Just add a test case (EventsTest.completeListenerCallbackTest_GET) to show the problem.

**Comment by danielflower** [comment]
I think that events test just needed `assertEventually(info::completedSuccessfully, is(true));` to remove the race condition.

**Comment by danielflower** [comment]
This is really good, thanks. Released on 0.61.1

**Comment by jaylu** [comment]
Thanks @danielflower , by the way. I was thought ResponseCompleteListener can be used to do statistic on response complete. e.g. check method, uri, status etc, if ppl using completedSuccessfully field at that point, if will get something inaccurate.

**Comment by danielflower** [comment]
Oh, i see. That does sound like a problem,I agree.

**Pull request merged**
