### PR TITLE
Allow https servers to enable OCSP stapling

### PR DESCRIPTION
**Pull request by robdann**
To allow resolution of CWE-299 (https://cwe.mitre.org/data/definitions/299.html)

### CODE REVIEW

**Comment by danielflower** [comment]
The netty method suggests that a valid tcnative dependency is needed to enable this, and if it isn't available it will throw an exception. So does this throw an exception if OCSP stapling is not supported? The javadoc should be updated to explain when this can be enabled and whether it throws exceptions or not.

**Comment by danielflower** [comment]
I've tried this by enabling it and using the tcnative Open SSL provider (`OpenSsl.isOcspSupported()` returns `true`) on muserver.io but according to https://www.ssllabs.com/ssltest/analyze.html?d=muserver.io stapling is not enabled.

I also tried it with just the JDK (it's on JDK 11) and no stapling either.

So I don't know how to actually get stapling working.

**Comment by robdann** [comment]
Maybe only certain cert providers do OCSP

**Comment by danielflower** [comment]
That cert is a letsencrypt cert. According to the SSL labs report:
image

...the OCSP URL is `http://r3.o.lencr.org` which is the letsencrypt OCSP according to https://letsencrypt.org/docs/lencr.org/

So OCSP is working, but it's not stapled (and I've seen examples of stapling with letsencrypt). The only hint I've found with netty is that the full cert chain needs to be available in the SSL cert, but looking at the letsencrypt cert for muserver.io I'm pretty sure the full chain is there.

**Comment by danielflower** [comment]
Having read a bit more, to enable OCSP stapling the server needs to make HTTP requests to the CA to get the signed revocation status info (this bit is covered in https://github.com/netty/netty/blob/4.0/example/src/main/java/io/netty/example/ocsp/OcspServerExample.java and the util class) and then return that in the SSL handshake, which I think requires having a custom trust manager. And just to complicate things, it may be different depending on whether it is the JDK or OpenSSL provider.

I tried setting OCSP enable to false with both OpenSSL and JDK providers and this had no effect: OCSP was still there (due to it being on the cert I believe) but stapling wasn't working.

So I have reverted this PR as it seems to have no effect.

**Pull request merged**
